### ISSUE TITLE
Create web3 starter project (web3 equivalent of a web2 todo app)

### ISSUE THREAD

**Issue by blakecduncan** [web3well/ethdk#5]
Developing a dApp for Ethereum involves working with several different technologies and protocols, which can be complex and require specialized knowledge. We aim to make an EthDK package that simplifies building on web3.  

Since we are still deciding what needs to be built, we want to create a web3 starter project as part of the exploration.  This project will be similar to what we might see for a full-stack web2 tutorial, like a to-do app.

The goal here is to be opinionated and make all the big decisions for the developer.  Here are some ideas of what we can build:

**Blog**
- Wallet: unsure
- Blockchain: optimism or arbitrum
- Hardhat: Could deploy blog contract
- Next.js and React
- IPFS
- The Graph Protocol

**NFT marketplace**
- wallet: unsure
- Blockchain: optimism or arbitrum
- Hardhat: deploy an erc721
- Next.js and React
- IPFS

**Social media application**
- Lens Protocol (deployed on Polygon)

**Social sign-in**
- Biconomy api
- Try to build our own with gnosis safe
- Make our own with bls-wallet
- Next.js and React

**Token app**
- Wallet: browser wallet 
- Hardhat: deploy erc20 
- Next.js and React

The final output from this task should be a small starter project that implements one of the above ideas.  From there, we should discuss ways that EthDK could make this app simpler.

**Comment by jacque006** [comment]
@blakecduncan ~is this issue still needed?~ nvm saw label, closing
